name: Automated Testing
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Tests
      run: |
          python find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
          python find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
          python find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
    - name: Compare Results
      run: |
          diff test_data/test1_actual.txt test_data/test1_expected.txt
          diff test_data/test2_actual.txt test_data/test2_expected.txt
          diff test_data/test3_actual.txt test_data/test3_expected.txt
